### PR TITLE
Update signature of accuracy.gts method for forecast change

### PR DESCRIPTION
**Pull request by mitchelloharawild**
Ref: https://github.com/robjhyndman/forecast/commit/6b9ab090cd01062460c285d17dd6bc6d6d310a48

### CODE REVIEW

**Comment by earowang** [comment]
Do I merge this now or hold for now?

**Comment by mitchelloharawild** [comment]
No rush, it'll be a revdep requirement of the next forecast package release.
Are you thinking of releasing soon for nn-mint?

**Comment by earowang** [comment]
Yes, will release soon.

On 26 Mar 2020, at 20:39, mitchelloharawild wrote:

> No rush, it'll be a revdep requirement of the next forecast package 
> release.
> Are you thinking of releasing soon for nn-mint?
>
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/earowang/hts/pull/50#issuecomment-604277004



Cheers,
Earo

**Comment by mitchelloharawild** [comment]
Alright, I'll work toward submitting a patch release of forecast tomorrow. This can be merged and in your cran-comments you can state that your release resolves check issues from changes to the forecast package.

**Comment by earowang** [comment]
any update on forecast release?

**Comment by mitchelloharawild** [comment]
Running revdep checks now.

**Comment by mitchelloharawild** [comment]
`forecast` has been submitted to CRAN and passed automatic checks.

**Pull request merged**
